### ISSUE TITLE
大哥你是怎么把fedora装到ryzen上的奥

### ISSUE THREAD

**Issue by wotmshuaisi** [yelanxin/netease-cloud-music-fedora-27#2]
我的ryzen 1400死活装不上，试了七八个发行版，除了arch和opensuse其他都装不上，而且即使装上了，也只能识别一个核心，假如把ACPI打开的话，系统就进不去了

**Comment by yelanxin** [comment]
直接装的，没有碰到任何问题啊。装完无法启动还是无法安装。

**Comment by wotmshuaisi** [comment]
无法安装

**Comment by yelanxin** [comment]
u盘安装还是刻盘。
是不是制作启动盘有问题。
可以贴一下出错的图片。
